name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./c
          file: ./c/Dockerfile
          push: true
          tags: ttbb/compile:c
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./c-ubuntu
          file: ./c-ubuntu/Dockerfile
          push: true
          tags: ttbb/compile:c-ubuntu
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./go
          file: ./go/Dockerfile
          push: true
          tags: ttbb/compile:go
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./jdk8
          file: ./jdk8/Dockerfile
          push: true
          tags: ttbb/compile:jdk8
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./jdk11
          file: ./jdk11/Dockerfile
          push: true
          tags: ttbb/compile:jdk11
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./jdk11-git
          file: ./jdk11-git/Dockerfile
          push: true
          tags: ttbb/compile:jdk11-git                    
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./jdk11-git-mvn
          file: ./jdk11-git-mvn/Dockerfile
          push: true
          tags: ttbb/compile:jdk11-git-mvn